# Generated by Django 4.1.1 on 2022-09-20 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_company_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="projects.company",
            ),
        ),
    ]
