# Generated by Django 4.1.1 on 2022-09-20 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_project_project"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="project",
            new_name="company",
        ),
    ]
