# Generated by Django 4.1.1 on 2022-09-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_rename_project_project_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="project",
            field=models.ManyToManyField(
                related_name="companies", to="projects.project"
            ),
        ),
    ]
