# Generated by Django 4.1.1 on 2022-09-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_alter_company_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
